---
- import_tasks: create_lv.yml
  when: docker_marathon_create_lv

- name: Pull Marathon Docker image
  docker_image:
    name: "{{ docker_marathon_image }}"

- name: Run Marathon container
  docker_container:
    name: "{{ docker_marathon_container_name }}"
    image: "{{ docker_marathon_image }}"
    command: --master {{ docker_marathon_master }} --zk {{ docker_marathon_zk }}
    restart_policy: always
    network_mode: host
