---
- name: Disable resolvconf service
  service:
    name: resolvconf
    state: stopped
    enabled: no

- name: Configure resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    mode: 0644
