- name: Add Docker repo key
  apt_key:
    url: "{{ docker_repo_key_url }}"
    state: present

- name: Add Docker repo
  apt_repository:
    repo: deb [arch=amd64] {{ docker_repo_url }} {{ docker_ubuntu_release }} stable
    state: present
    filename: docker

- name: Install Docker
  apt:
    name: "{{ docker_package }}"
    state: present
    update_cache: yes
