---
- name: Generate ssh keys
  user:
    name: postgres
    generate_ssh_key: yes
    state: present

- name: Configure postgresql.conf
  lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_name }}/postgresql.conf
    regexp: "^{{ item.key }} .+$"
    line: "{{ item.key }} = {{ item.value }}"
  loop: "{{ query('dict', postgresql_barman_options | default({})) }}"
  notify: configuration changed

- name: Configure pg_hba.conf
  lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_name }}/pg_hba.conf
    line: "{{ item.type }}\t{{ item.database }}\t{{ item.user }}\t{{ item.address }}\t{{ item.method }}"
  loop: "{{ postgresql_barman_hba }}"
  notify: configuration changed
