- name: Create admin accounts
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
  loop: "{{ admin_ssh_keys }}"

- name: Set authorized key
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  loop: "{{ admin_ssh_keys }}"

- name: Sudo NOPASSWD
  lineinfile:
    dest: /etc/sudoers.d/{{ item.name }}
    state: present
    create: yes
    line: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
  loop: "{{ admin_ssh_keys }}"
