---
- name: Create logical volume
  lvol:
    vg: "{{ item.vg_name | default('shared') }}"
    lv: "{{ item.lv_name }}"
    size: "{{ item.lv_size }}"
  notify: mkfs
  loop: "{{ lvmount }}"

#- meta: flush_handlers
- name: mkfs
  filesystem:
    dev: /dev/{{ item.vg_name | default('shared') }}/{{ item.lv_name }}
    fstype: "{{ item.fstype }}"
  loop: "{{ lvmount }}"

- name: Create mountpoint
  file:
    path: "{{ item.mount_path }}"
    state: directory
  loop: "{{ lvmount }}"

- name: Mount logical volume
  mount:
    src: /dev/{{ item.vg_name | default('shared') }}/{{ item.lv_name }}
    path: "{{ item.mount_path }}"
    fstype: "{{ item.fstype }}"
    opts: noatime
    state: mounted
  loop: "{{ lvmount }}"

- name: Set mountpoint attributes
  file:
    path: "{{ item.mount_path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  loop: "{{ lvmount }}"
