---
- import_tasks: create_lv.yml
  when: postgresql_create_lv

- name: Install depended packages
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add PostgreSQL repo key
  apt_key:
    url: "{{ postgresql_repo_key_url }}"
    state: present

- name: Add Docker repo
  apt_repository:
    repo: deb {{ postgresql_repo_url }} {{ postgresql_ubuntu_release }}-pgdg main
    state: present
    filename: pgdg
  notify:
    - update caches

- meta: flush_handlers

- name: Install PostgreSQL packages
  apt:
    name: "{{ item }}"
    state: present
#    update_cache: yes
  loop: "{{ postgresql_packages }}"

- name: Configure postgresql.conf
  lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_name }}/postgresql.conf
    regexp: "^{{ item.key }} .+$"
    line: "{{ item.key }} = {{ item.value }}"
  loop: "{{ query('dict', postgresql_options | default({})) }}"

- name: Configure pg_hba.conf
  lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/{{ postgresql_cluster_name }}/pg_hba.conf
    line: "{{ item.type }}\t{{ item.database }}\t{{ item.user }}\t{{ item.address }}\t{{ item.method }}"
  loop: "{{ postgresql_hba }}"

- pause:
    prompt: "Make sure primary db replication settings accepted. Restart primary db service if needed"
  when: postgresql_init_standby

- import_tasks: init_standby.yml
  when: postgresql_init_standby and postgresql_standby_host == ansible_default_ipv4.address
